name: CD

on:
  push:
    branches:
      - main

env:
  CI: true
  CLOUDTRUTH_API_KEY: ${{ secrets.CT_API_KEY }}

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cloudtruth/cli-action@v1
        with:
          version: 0.2.0

      - name: Install Atmos
        run: sudo gem install --no-document simplygenius-atmos

      - name: Setup Atmos
        run: |
          mkdir -p config
          cloudtruth -e production template get deploy.atmos_yml > config/atmos.yml

      - name: Deploy cloudformation template to S3
        run: |
          source <(cloudtruth -e production template get deploy.aws_credentials_env)
          source <(cloudtruth -e production template get deploy.package_env)
          BUCKET_PATH=cloudformation/cloudtruth-access
          CF_TMPL=cloudTruth_AWS_access.json
          atmos -e production auth_exec aws s3 cp --acl public-read ${CF_TMPL} s3://${BUCKET_NAME}/${BUCKET_PATH}/
          atmos -e production auth_exec aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/${BUCKET_PATH}/${CF_TMPL}"
