name: CD

on:
  push:
    branches:
      - main

env:
  CI: true
  CLOUDTRUTH_API_KEY: ${{ secrets.CT_API_KEY }}

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set environment from cloudtruth
        uses: cloudtruth/configure-action@v2
        with:
          apikey: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: "deploy"
          environment: "production"

      - name: Install Atmos
        run: sudo gem install --no-document simplygenius-atmos

      - name: Setup Atmos
        run: |
          mkdir -p config
          echo -e "${ATMOS_YML}" > config/atmos.yml

      - name: Deploy cloudformation template to S3
        run: |
          BUCKET_PATH=cloudformation/cloudtruth-access
          CF_TMPL=cloudTruth_AWS_access.json
          atmos -e production auth_exec aws s3 cp --acl public-read ${CF_TMPL} s3://${PACKAGES_BUCKET_NAME}/${BUCKET_PATH}/
          atmos -e production auth_exec aws cloudfront create-invalidation --distribution-id ${PACKAGES_DISTRIBUTION_ID} --paths "/${BUCKET_PATH}/${CF_TMPL}"
